In [6]:
import pandas as pd
import numpy as np
from scipy.optimize import minimize
from scipy.stats.mstats import gmean
from itertools import combinations
from matplotlib import pyplot as plt

In [26]:
def define_outlier_element(D, method):
    n = D.shape[0]

    if method == "shortened":

        def get_CI(D, n):
            w, v = np.linalg.eig(D)
            lambda_max = np.max(w).astype(np.float32)
            return (lambda_max - n) / (n - 1)

        cid = []
        for i in range(D.shape[0]):
            indices = list(range(0, i)) + list(range(i + 1, matrix.shape[0]))
            short = matrix[indices, :][:, indices]
            cid.append(get_CI(short, n - 1))
            print(f"{i} CI: {cid[-1]}")

        cid = np.array(cid)
        j, i = np.argpartition(cid, 2)[:2]
        return np.array([i, j])

    if method == "correlation":
        corrs_i = np.array(
            [
                np.mean([np.corrcoef(D[i], D[j]) for j in range(n) if i != j])
                for i in range(n)
            ]
        )
        corrs_j = np.array(
            [
                np.mean([np.corrcoef(D[:, i], D[:, j]) for j in range(n) if i != j])
                for i in range(n)
            ]
        )
        i = np.argmin(corrs_i)
        j = np.argmin(corrs_j)
        return np.array([i, j])

    if method == "chi":
        T = np.array(
            [
                [(D[i].sum() * D[:, j].sum()) / (D.sum()) for j in range(n)]
                for i in range(n)
            ]
        )
        deltas = ((D - T) ** 2) / T
        mean = deltas.mean()
        sigma = deltas.std()
        deltas_mask = np.array(
            [
                [
                    1 if not (mean - sigma < deltas[i, j] < mean + sigma) else 0
                    for j in range(n)
                ]
                for i in range(n)
            ]
        )
        return np.argwhere(deltas_mask)

    if method == "transitive":
        # He = [np.array([D[i,j], D[j,k], D[i,k]]) for i in range(n) for j in range(n) for k in range(n) if i<j<k]
        # Det = [(D[i,j]*D[j,k]/D[i,k]) + (D[i,k]/(D[i,j]*D[j,k])) - 2 for i in range(n) for j in range(n) for k in range(n) if i<j<k]
        S_ij = np.array(
            [
                (
                    (D[i, j] * D[j, :] / D[i, :]) + (D[i, :] / (D[i, j] * D[j, :])) - 2
                ).sum()
                for i in range(n)
                for j in range(n)
                if i < j
            ]
        )
        indices = [np.array([i, j]) for i in range(n) for j in range(n) if i < j][
            S_ij.argmax()
        ]
        return indices
    
    if method == "outflow":
        F_plus = np.array([(D[i, :] > 1).sum() for i in range(n)])
        F_minus = np.array([(D[:, i] > 1).sum() for i in range(n)])
        print(f"F_plus: {F_plus}")
        print(f"F_minus: {F_minus}")
        res = np.empty((n, n))
        for i in range(n):
            for j in range(n):
                res[i, j] = max(F_plus[j] - F_plus[i], F_minus[i] - F_minus[j])

        if len(np.argwhere(res == res.max())) <= 1:
            return np.argwhere(res == res.max())
        else:
            print("2+ elements satisfy ")
            gamma = {}
            for i in range(n):
                for j in range(n):
                    gamma[(i,j)] = 0
                    for k in range(n):
                        if (i != j and j != k and i != k):
                            gamma[(i,j)]+=np.log(D[i,j]) - np.log(D[i,k]*D[k,j])
                    gamma[(i,j)] /= (n-2)

            result = max(gamma, key=lambda key: gamma[key])
            return np.array(result)
        
    raise ValueError("Method should be one of: 'outflow', 'transitive', 'chi', 'correlation', 'shortened'.")
    

In [27]:
matrix = np.array([[1, 1, 1/2, 4, 3, 1/3, 2],
                   [1, 1, 1/2, 4, 3, 1/3, 2],
                   [2, 7, 1, 8, 6, 1/2, 4],
                   [1/4, 1/4, 1/8, 1, 1, 7, 1/2],
                   [1/3, 1/3, 1/6, 1, 1, 1/9, 1],
                   [3, 3, 2, 1/7, 9, 1, 6],
                   [1/2, 1/2, 1/4, 2, 1, 1/6, 1]])

define_outlier_element(matrix, 'shortened')

0 CI: 0.7903690338134766
1 CI: 0.7279794692993165
2 CI: 0.6933403015136719
3 CI: 0.08690452575683594
4 CI: 0.810521125793457
5 CI: 0.08439168930053711
6 CI: 0.7865217208862305


<ipython-input-26-1c5ccba42b5a>:8: ComplexWarning: Casting complex values to real discards the imaginary part
  lambda_max = np.max(w).astype(np.float32)


array([3, 5])

In [28]:
define_outlier_element(matrix, "correlation")

array([3, 5])

In [29]:
define_outlier_element(matrix, "chi")

array([[3, 5]])

In [30]:
define_outlier_element(matrix, "transitive")

array([3, 5])

In [31]:
define_outlier_element(matrix, "outflow")

F_plus: [3 3 5 1 0 5 1]
F_minus: [2 2 1 4 4 1 4]
2 elements satisfy


array([3, 5])

In [4]:

def iterative_improvement(D, alphas, method):
    buffer = {"delta": [], "sigma": [], "loss": []}
    n = D.shape[0]
    
    def MRCI(n):
        table1 = [0, 0, 0.52, 0.89, 1.11, 1.25, 1.35, 1.40, 1.45, 1.49, 1.52, 1.54, 1.56, 1.58, 1.59]
        if n >= len(table1):
            raise ValueError("n too chonky")
        return table1[n-1]
    
    def CR(D):
        return ((np.linalg.eigvals(D)[0] - n) / (n - 1)) / MRCI(n)
    
    def get_eigvector(D):

        lambda_max = np.linalg.eigvals(D)[0]

        def objective(w):

            return np.linalg.norm(D @ w - lambda_max * w)

        bnds = tuple((0, None) for i in range(n))
        w0 = np.ones(n)
        result = minimize(objective, w0, bounds=bnds)
        return result["x"]

    def criterion_inf(D, D_updated):
        return np.linalg.norm(D - D_updated, ord=np.inf)

    def criterion_l2(D, D_updated):
        return np.linalg.norm(D - D_updated) / n

    for alpha in alphas:
        D_updated = D.copy()
        print(f"alpha={alpha}")

        buffer["delta"].append([])
        buffer["sigma"].append([])
        buffer["loss"].append([])
        counter = 0
        
        while CR(D_updated) > 0.1:
            counter += 1
            w = get_eigvector(D_updated)

            if method == "WGMM":
                D_updated = np.array(
                    [
                        [
                            ((D_updated[i, j]) ** alpha)
                            * ((w[i] / w[j])) ** (1 - alpha)
                            for j in range(n)
                        ]
                        for i in range(n)
                    ]
                )
                
            if method == "WAMM":
                D_updated = np.array(
                    [
                        [
                            ((D_updated[i, j]) * alpha) + ((w[i] / w[j])) * (1 - alpha)
                            if j > i
                            else 1.0
                            / (
                                ((D_updated[j, i]) * alpha)
                                + ((w[j] / w[i])) * (1 - alpha)
                            )
                            for j in range(n)
                        ]
                        for i in range(n)
                    ]
                )
                
            sigma = criterion_l2(D, D_updated)
            delta = criterion_inf(D, D_updated)
            loss = CR(D_updated)
            print(f"iteration {counter}")
            print(
                f"delta: {criterion_inf(D, D_updated)}, sigma: {criterion_l2(D, D_updated)}, loss: {loss}"
            )
            print(f"w:{np.round(w, 5)}")
            print(f"D: {np.round(D_updated, 3)}")

            buffer["delta"][-1].append(delta)
            buffer["sigma"][-1].append(sigma)
            buffer["loss"][-1].append(loss)

    print(len(buffer["delta"]))
    fig, axes = plt.subplots(3, 1, figsize=(12, 12))

    for deltas in buffer["delta"]:
        axes[0].plot(deltas)
        axes[0].set_title("delta")
        axes[0].legend(alphas)

    for sigmas in buffer["sigma"]:
        axes[1].plot(sigmas)
        axes[1].set_title("sigma")
        axes[1].legend(alphas)

    for losses in buffer["loss"]:
        axes[2].plot(losses)
        axes[2].set_title("loss")
        axes[2].legend(alphas)
        
    return D_updated

In [5]:
D_u = iterative_improvement(matrix, [0.999], "WAMM")

alpha=0.999
iteration 1
delta: 5.009999582470986, sigma: 0.7142389604149242, loss: (0.4537648695116715+0j)
w:[0.90443 0.90443 2.19867 1.19344 0.27852 1.52138 0.43949]
D: [[1.    1.    0.5   3.997 3.    0.334 2.   ]
 [1.    1.    0.5   3.997 3.    0.334 2.   ]
 [2.    2.    1.    7.994 6.002 0.501 4.001]
 [0.25  0.25  0.125 1.    1.003 6.994 0.502]
 [0.333 0.333 0.167 0.997 1.    0.111 1.   ]
 [2.998 2.998 1.996 0.143 8.994 1.    5.997]
 [0.5   0.5   0.25  1.991 1.    0.167 1.   ]]
iteration 2
delta: 5.017700646995159, sigma: 0.714254250415464, loss: (0.45275201874614596+0j)
w:[0.90862 0.90862 1.79435 1.19416 0.27907 1.48329 0.44043]
D: [[1.    1.    0.5   3.994 3.001 0.334 2.   ]
 [1.    1.    0.5   3.994 3.001 0.334 2.   ]
 [2.    2.    1.    7.987 6.002 0.502 4.001]
 [0.25  0.25  0.125 1.    1.007 6.988 0.504]
 [0.333 0.333 0.167 0.993 1.    0.111 0.999]
 [2.995 2.995 1.993 0.143 8.988 1.    5.995]
 [0.5   0.5   0.25  1.982 1.001 0.167 1.   ]]
iteration 3
delta: 5.025408644122842, si

iteration 20
delta: 5.157700569950443, sigma: 0.7157636769473161, loss: (0.4351647723550028+0j)
w:[0.91196 0.91196 1.80097 1.19251 0.27492 1.47479 0.42851]
D: [[1.    1.    0.5   3.936 3.006 0.339 2.002]
 [1.    1.    0.5   3.936 3.006 0.339 2.002]
 [2.    2.    1.    7.872 6.011 0.514 4.004]
 [0.254 0.254 0.127 1.    1.066 6.877 0.545]
 [0.333 0.333 0.166 0.938 1.    0.113 0.993]
 [2.951 2.951 1.944 0.145 8.88  1.    5.949]
 [0.5   0.5   0.25  1.837 1.007 0.168 1.   ]]
iteration 21
delta: 5.165571908993943, sigma: 0.7159114724689816, loss: (0.43422190386836934+0j)
w:[0.91214 0.91214 1.80133 1.19241 0.27471 1.47434 0.4279 ]
D: [[1.    1.    0.5   3.933 3.006 0.339 2.002]
 [1.    1.    0.5   3.933 3.006 0.339 2.002]
 [2.    2.    1.    7.865 6.012 0.515 4.004]
 [0.254 0.254 0.127 1.    1.069 6.871 0.547]
 [0.333 0.333 0.166 0.936 1.    0.113 0.992]
 [2.948 2.948 1.941 0.146 8.874 1.    5.946]
 [0.5   0.5   0.25  1.829 1.008 0.168 1.   ]]
iteration 22
delta: 5.173448795493457, sigma: 0.7

iteration 39
delta: 5.308140913213733, sigma: 0.7195867596756348, loss: (0.4178177087530067+0j)
w:[0.91529 0.91529 1.80761 1.19055 0.27109 1.46654 0.41763]
D: [[1.    1.    0.5   3.876 3.012 0.344 2.005]
 [1.    1.    0.5   3.876 3.012 0.344 2.005]
 [1.999 1.999 1.    7.752 6.022 0.528 4.009]
 [0.258 0.258 0.129 1.    1.128 6.763 0.587]
 [0.332 0.332 0.166 0.887 1.    0.114 0.986]
 [2.905 2.905 1.895 0.148 8.773 1.    5.902]
 [0.499 0.499 0.249 1.703 1.014 0.169 1.   ]]
iteration 40
delta: 5.316106493246752, sigma: 0.7198437268126617, loss: (0.4169365651444218+0j)
w:[0.91546 0.91546 1.80794 1.19044 0.2709  1.46613 0.4171 ]
D: [[1.    1.    0.5   3.873 3.012 0.345 2.005]
 [1.    1.    0.5   3.873 3.012 0.345 2.005]
 [1.999 1.999 1.    7.746 6.023 0.529 4.009]
 [0.258 0.258 0.129 1.    1.131 6.757 0.59 ]
 [0.332 0.332 0.166 0.884 1.    0.114 0.986]
 [2.903 2.903 1.892 0.148 8.767 1.    5.9  ]
 [0.499 0.499 0.249 1.696 1.014 0.169 1.   ]]
iteration 41
delta: 5.324076399167174, sigma: 0.72

 [0.498 0.498 0.249 1.58  1.021 0.171 1.   ]]
iteration 60
delta: 5.476246615156693, sigma: 0.7260125344493812, loss: (0.3999291403058782+0j)
w:[0.91877 0.91877 1.81452 1.18818 0.2674  1.45817 0.40729]
D: [[1.    1.    0.5   3.812 3.02  0.35  2.009]
 [1.    1.    0.5   3.812 3.02  0.35  2.009]
 [1.999 1.999 1.    7.622 6.037 0.543 4.017]
 [0.262 0.262 0.131 1.    1.196 6.639 0.635]
 [0.331 0.331 0.166 0.836 1.    0.115 0.979]
 [2.856 2.856 1.843 0.151 8.662 1.    5.853]
 [0.498 0.498 0.249 1.574 1.021 0.171 1.   ]]
iteration 61
delta: 5.484290531657452, sigma: 0.726369016883077, loss: (0.3991081976425653+0j)
w:[0.91893 0.91893 1.81484 1.18806 0.26723 1.45778 0.40683]
D: [[1.    1.    0.5   3.809 3.021 0.35  2.01 ]
 [1.    1.    0.5   3.809 3.021 0.35  2.01 ]
 [1.999 1.999 1.    7.616 6.038 0.543 4.017]
 [0.263 0.263 0.131 1.    1.199 6.634 0.637]
 [0.331 0.331 0.166 0.834 1.    0.116 0.979]
 [2.854 2.854 1.841 0.151 8.657 1.    5.851]
 [0.498 0.498 0.249 1.569 1.021 0.171 1.   ]]
itera

iteration 80
delta: 5.637651663379265, sigma: 0.7339110039989748, loss: (0.3840023660363477+0j)
w:[0.92188 0.92188 1.82072 1.18574 0.26434 1.4508  0.39882]
D: [[1.    1.    0.5   3.751 3.029 0.356 2.015]
 [1.    1.    0.5   3.751 3.029 0.356 2.015]
 [1.998 1.998 1.    7.502 6.053 0.557 4.027]
 [0.267 0.267 0.133 1.    1.261 6.524 0.681]
 [0.33  0.33  0.165 0.793 1.    0.117 0.973]
 [2.811 2.811 1.797 0.153 8.563 1.    5.809]
 [0.496 0.496 0.248 1.469 1.028 0.172 1.   ]]
iteration 81
delta: 5.645747322945705, sigma: 0.7343459378251068, loss: (0.3832321992179487+0j)
w:[0.92203 0.92203 1.82102 1.18561 0.2642  1.45045 0.39842]
D: [[1.    1.    0.5   3.749 3.03  0.356 2.015]
 [1.    1.    0.5   3.749 3.03  0.356 2.015]
 [1.998 1.998 1.    7.496 6.054 0.557 4.027]
 [0.267 0.267 0.133 1.    1.264 6.518 0.683]
 [0.33  0.33  0.165 0.791 1.    0.117 0.973]
 [2.809 2.809 1.794 0.153 8.558 1.    5.807]
 [0.496 0.496 0.248 1.464 1.028 0.172 1.   ]]
iteration 82
delta: 5.653845025180997, sigma: 0.73

iteration 99
delta: 5.791771159690547, sigma: 0.7427550694511709, loss: (0.36976545261647253+0j)
w:[0.92374 0.92374 1.82443 1.18208 0.26153 1.44283 0.39142]
D: [[1.    1.    0.501 3.696 3.038 0.361 2.021]
 [1.    1.    0.501 3.696 3.038 0.361 2.021]
 [1.998 1.998 1.    7.39  6.07  0.57  4.038]
 [0.271 0.271 0.135 1.    1.322 6.417 0.725]
 [0.329 0.329 0.165 0.756 1.    0.118 0.967]
 [2.77  2.77  1.755 0.156 8.474 1.    5.768]
 [0.495 0.495 0.248 1.38  1.034 0.173 1.   ]]
iteration 100
delta: 5.7998973530733515, sigma: 0.7432526508172892, loss: (0.36903852905638945+0j)
w:[0.92398 0.92398 1.8249  1.18207 0.26143 1.44265 0.39111]
D: [[1.    1.    0.501 3.693 3.039 0.361 2.021]
 [1.    1.    0.501 3.693 3.039 0.361 2.021]
 [1.998 1.998 1.    7.384 6.071 0.571 4.038]
 [0.271 0.271 0.135 1.    1.325 6.411 0.727]
 [0.329 0.329 0.165 0.755 1.    0.118 0.967]
 [2.768 2.768 1.753 0.156 8.47  1.    5.766]
 [0.495 0.495 0.248 1.376 1.034 0.173 1.   ]]
iteration 101
delta: 5.808024686099909, sigma:

iteration 117
delta: 5.9381810656633345, sigma: 0.7521526344898606, loss: (0.35700160465839176+0j)
w:[0.92798 0.92798 1.83284 1.18185 0.25988 1.43974 0.38631]
D: [[1.    1.    0.501 3.644 3.047 0.366 2.027]
 [1.    1.    0.501 3.644 3.047 0.366 2.027]
 [1.998 1.998 1.    7.285 6.087 0.582 4.05 ]
 [0.274 0.274 0.137 1.    1.379 6.317 0.766]
 [0.328 0.328 0.164 0.725 1.    0.119 0.962]
 [2.732 2.732 1.717 0.158 8.395 1.    5.732]
 [0.493 0.493 0.247 1.306 1.04  0.174 1.   ]]
iteration 118
delta: 5.94632109361437, sigma: 0.7527007269147694, loss: (0.35631181084135444+0j)
w:[0.92821 0.92821 1.8333  1.18183 0.2598  1.43958 0.38604]
D: [[1.    1.    0.501 3.641 3.048 0.366 2.028]
 [1.    1.    0.501 3.641 3.048 0.366 2.028]
 [1.998 1.998 1.    7.28  6.088 0.583 4.05 ]
 [0.275 0.275 0.137 1.    1.383 6.311 0.768]
 [0.328 0.328 0.164 0.723 1.    0.119 0.962]
 [2.73  2.73  1.715 0.158 8.39  1.    5.73 ]
 [0.493 0.493 0.247 1.302 1.04  0.175 1.   ]]
iteration 119
delta: 5.9544614891791205, sigma

iteration 138
delta: 6.109146250870314, sigma: 0.7641765369998476, loss: (0.3429156832085276+0j)
w:[0.93278 0.93278 1.84236 1.18145 0.25825 1.43653 0.38116]
D: [[1.    1.    0.501 3.584 3.059 0.372 2.036]
 [1.    1.    0.501 3.584 3.059 0.372 2.036]
 [1.997 1.997 1.    7.166 6.108 0.597 4.065]
 [0.279 0.279 0.14  1.    1.446 6.202 0.814]
 [0.327 0.327 0.164 0.692 1.    0.12  0.956]
 [2.689 2.689 1.676 0.161 8.306 1.    5.69 ]
 [0.491 0.491 0.246 1.228 1.046 0.176 1.   ]]
iteration 139
delta: 6.1172857789427795, sigma: 0.7647744518939172, loss: (0.3422651574799926+0j)
w:[0.93301 0.93301 1.8428  1.18143 0.25818 1.43638 0.38094]
D: [[1.    1.    0.501 3.581 3.059 0.372 2.036]
 [1.    1.    0.501 3.581 3.059 0.372 2.036]
 [1.997 1.997 1.    7.161 6.109 0.597 4.066]
 [0.279 0.279 0.14  1.    1.449 6.197 0.816]
 [0.327 0.327 0.164 0.69  1.    0.12  0.956]
 [2.687 2.687 1.674 0.161 8.302 1.    5.689]
 [0.491 0.491 0.246 1.225 1.046 0.176 1.   ]]
iteration 140
delta: 6.125424869650278, sigma: 

iteration 157
delta: 6.263688518609717, sigma: 0.7758879776411673, loss: (0.3308507591687097+0j)
w:[0.93699 0.93699 1.85071 1.18099 0.257   1.43394 0.37715]
D: [[1.    1.    0.501 3.532 3.069 0.377 2.044]
 [1.    1.    0.501 3.532 3.069 0.377 2.044]
 [1.997 1.997 1.    7.061 6.128 0.61  4.08 ]
 [0.283 0.283 0.142 1.    1.505 6.101 0.857]
 [0.326 0.326 0.163 0.665 1.    0.122 0.951]
 [2.651 2.651 1.64  0.164 8.23  1.    5.655]
 [0.489 0.489 0.245 1.166 1.052 0.177 1.   ]]
iteration 158
delta: 6.271813799132036, sigma: 0.776523800756098, loss: (0.3302325177033353+0j)
w:[0.93721 0.93721 1.85115 1.18096 0.25694 1.43381 0.37696]
D: [[1.    1.    0.501 3.529 3.07  0.377 2.044]
 [1.    1.    0.501 3.529 3.07  0.377 2.044]
 [1.997 1.997 1.    7.055 6.129 0.61  4.081]
 [0.283 0.283 0.142 1.    1.508 6.096 0.86 ]
 [0.326 0.326 0.163 0.663 1.    0.122 0.951]
 [2.649 2.649 1.638 0.164 8.226 1.    5.653]
 [0.489 0.489 0.245 1.163 1.052 0.177 1.   ]]
iteration 159
delta: 6.279937995456393, sigma: 0.

iteration 176
delta: 6.4178531495973905, sigma: 0.7882659333411234, loss: (0.3193746477669255+0j)
w:[0.94109 0.94109 1.85883 1.18043 0.25595 1.43161 0.37366]
D: [[1.    1.    0.501 3.48  3.081 0.382 2.053]
 [1.    1.    0.501 3.48  3.081 0.382 2.053]
 [1.996 1.996 1.    6.957 6.148 0.623 4.096]
 [0.287 0.287 0.144 1.    1.563 6.002 0.901]
 [0.325 0.325 0.163 0.64  1.    0.123 0.946]
 [2.615 2.615 1.606 0.167 8.158 1.    5.62 ]
 [0.487 0.487 0.244 1.11  1.057 0.178 1.   ]]
iteration 177
delta: 6.425952537097785, sigma: 0.7889338431082782, loss: (0.31878602219010516+0j)
w:[0.9413  0.9413  1.85925 1.1804  0.2559  1.43149 0.37349]
D: [[1.    1.    0.501 3.477 3.081 0.383 2.053]
 [1.    1.    0.501 3.477 3.081 0.383 2.053]
 [1.996 1.996 1.    6.952 6.15  0.623 4.097]
 [0.288 0.288 0.144 1.    1.566 5.997 0.903]
 [0.325 0.325 0.163 0.639 1.    0.123 0.945]
 [2.613 2.613 1.604 0.167 8.154 1.    5.618]
 [0.487 0.487 0.244 1.108 1.058 0.178 1.   ]]
iteration 178
delta: 6.434050264041761, sigma:

iteration 197
delta: 6.587554721980848, sigma: 0.8025982011598266, loss: (0.3073184268181885+0j)
w:[0.94548 0.94548 1.86754 1.17972 0.25499 1.4293  0.37034]
D: [[1.    1.    0.501 3.424 3.093 0.388 2.063]
 [1.    1.    0.501 3.424 3.093 0.388 2.063]
 [1.996 1.996 1.    6.845 6.172 0.637 4.115]
 [0.292 0.292 0.146 1.    1.627 5.894 0.948]
 [0.323 0.323 0.162 0.615 1.    0.124 0.94 ]
 [2.576 2.576 1.57  0.17  8.081 1.    5.583]
 [0.485 0.485 0.243 1.055 1.063 0.179 1.   ]]
iteration 198
delta: 6.5956134850553765, sigma: 0.8032957307700818, loss: (0.30675982962302245+0j)
w:[0.94569 0.94569 1.86795 1.17968 0.25494 1.4292  0.37019]
D: [[1.    1.    0.501 3.422 3.094 0.388 2.063]
 [1.    1.    0.501 3.422 3.094 0.388 2.063]
 [1.996 1.996 1.    6.84  6.173 0.638 4.116]
 [0.292 0.292 0.146 1.    1.63  5.889 0.95 ]
 [0.323 0.323 0.162 0.614 1.    0.124 0.94 ]
 [2.574 2.574 1.569 0.17  8.077 1.    5.581]
 [0.485 0.485 0.243 1.053 1.064 0.179 1.   ]]
iteration 199
delta: 6.603670025098127, sigma:

iteration 218
delta: 6.756289676809791, sigma: 0.8174980485590982, loss: (0.2958674257787637+0j)
w:[0.94974 0.94974 1.87599 1.17892 0.2542  1.42725 0.36748]
D: [[1.    1.    0.501 3.37  3.106 0.394 2.073]
 [1.    1.    0.501 3.37  3.106 0.394 2.073]
 [1.995 1.995 1.    6.736 6.197 0.651 4.135]
 [0.297 0.297 0.148 1.    1.689 5.789 0.995]
 [0.322 0.322 0.161 0.592 1.    0.125 0.935]
 [2.539 2.539 1.536 0.173 8.007 1.    5.548]
 [0.482 0.482 0.242 1.005 1.069 0.18  1.   ]]
iteration 219
delta: 6.764296724434199, sigma: 0.8182198902254306, loss: (0.29533637906367854+0j)
w:[0.94994 0.94994 1.87638 1.17887 0.25416 1.42716 0.36736]
D: [[1.    1.    0.501 3.367 3.107 0.394 2.074]
 [1.    1.    0.501 3.367 3.107 0.394 2.074]
 [1.995 1.995 1.    6.731 6.198 0.652 4.136]
 [0.297 0.297 0.149 1.    1.692 5.784 0.997]
 [0.322 0.322 0.161 0.591 1.    0.125 0.935]
 [2.537 2.537 1.535 0.173 8.004 1.    5.546]
 [0.482 0.482 0.242 1.003 1.07  0.18  1.   ]]
iteration 220
delta: 6.772301057441905, sigma: 

iteration 238
delta: 6.915890681514109, sigma: 0.8321206401663194, loss: (0.2854796615917918+0j)
w:[0.95368 0.95368 1.88379 1.17807 0.25359 1.42549 0.36514]
D: [[1.    1.    0.501 3.319 3.119 0.399 2.084]
 [1.    1.    0.501 3.319 3.119 0.399 2.084]
 [1.995 1.995 1.    6.634 6.221 0.664 4.155]
 [0.301 0.301 0.151 1.    1.748 5.69  1.039]
 [0.321 0.321 0.161 0.572 1.    0.126 0.93 ]
 [2.504 2.504 1.506 0.176 7.941 1.    5.515]
 [0.48  0.48  0.241 0.963 1.075 0.181 1.   ]]
iteration 239
delta: 6.923839454754908, sigma: 0.8328613539040312, loss: (0.2849728366085104+0j)
w:[0.95388 0.95388 1.88418 1.17803 0.25356 1.42541 0.36504]
D: [[1.    1.    0.501 3.317 3.12  0.4   2.084]
 [1.    1.    0.501 3.317 3.12  0.4   2.084]
 [1.995 1.995 1.    6.629 6.222 0.665 4.156]
 [0.302 0.302 0.151 1.    1.75  5.686 1.041]
 [0.321 0.321 0.161 0.571 1.    0.126 0.93 ]
 [2.503 2.503 1.504 0.176 7.937 1.    5.513]
 [0.48  0.48  0.241 0.961 1.075 0.181 1.   ]]
iteration 240
delta: 6.931785103818705, sigma: 0

iteration 256
delta: 7.058475414777653, sigma: 0.8455753838677031, loss: (0.2765314328434123+0j)
w:[0.95713 0.95713 1.89064 1.17726 0.25315 1.42406 0.36331]
D: [[1.    1.    0.501 3.274 3.131 0.404 2.093]
 [1.    1.    0.501 3.274 3.131 0.404 2.093]
 [1.995 1.995 1.    6.544 6.243 0.676 4.174]
 [0.305 0.305 0.153 1.    1.799 5.604 1.078]
 [0.319 0.319 0.16  0.556 1.    0.127 0.926]
 [2.474 2.474 1.48  0.178 7.883 1.    5.486]
 [0.478 0.478 0.24  0.928 1.08  0.182 1.   ]]
iteration 257
delta: 7.066365135739029, sigma: 0.846329948430567, loss: (0.2760449173039593+0j)
w:[0.95732 0.95732 1.89101 1.17721 0.25313 1.42398 0.36322]
D: [[1.    1.    0.501 3.272 3.132 0.404 2.094]
 [1.    1.    0.501 3.272 3.132 0.404 2.094]
 [1.995 1.995 1.    6.54  6.244 0.677 4.175]
 [0.306 0.306 0.153 1.    1.802 5.599 1.08 ]
 [0.319 0.319 0.16  0.555 1.    0.127 0.926]
 [2.473 2.473 1.478 0.179 7.879 1.    5.485]
 [0.478 0.478 0.24  0.926 1.08  0.182 1.   ]]
iteration 258
delta: 7.074251407880808, sigma: 0.

iteration 276
delta: 7.215595903955585, sigma: 0.8607887530246033, loss: (0.2670039151345532+0j)
w:[0.96086 0.96086 1.89803 1.17628 0.25276 1.4226  0.36155]
D: [[1.    1.    0.501 3.226 3.144 0.409 2.104]
 [1.    1.    0.501 3.226 3.144 0.409 2.104]
 [1.994 1.994 1.    6.447 6.267 0.689 4.194]
 [0.31  0.31  0.155 1.    1.856 5.509 1.121]
 [0.318 0.318 0.16  0.539 1.    0.128 0.922]
 [2.442 2.442 1.452 0.182 7.821 1.    5.455]
 [0.475 0.475 0.238 0.892 1.085 0.183 1.   ]]
iteration 277
delta: 7.223413574333809, sigma: 0.8615556352359338, loss: (0.266538488508106+0j)
w:[0.96105 0.96105 1.89839 1.17623 0.25275 1.42254 0.36147]
D: [[1.    1.    0.501 3.223 3.145 0.41  2.105]
 [1.    1.    0.501 3.223 3.145 0.41  2.105]
 [1.994 1.994 1.    6.442 6.269 0.689 4.196]
 [0.31  0.31  0.155 1.    1.859 5.504 1.123]
 [0.318 0.318 0.16  0.538 1.    0.128 0.921]
 [2.44  2.44  1.45  0.182 7.817 1.    5.454]
 [0.475 0.475 0.238 0.891 1.085 0.183 1.   ]]
iteration 278
delta: 7.231227480013907, sigma: 0.

iteration 294
delta: 7.355726279683622, sigma: 0.8746692642880941, loss: (0.2587790050933214+0j)
w:[0.96413 0.96413 1.9045  1.17535 0.2525  1.42141 0.36017]
D: [[1.    1.    0.502 3.183 3.156 0.414 2.114]
 [1.    1.    0.502 3.183 3.156 0.414 2.114]
 [1.994 1.994 1.    6.361 6.29  0.7   4.214]
 [0.314 0.314 0.157 1.    1.906 5.425 1.159]
 [0.317 0.317 0.159 0.525 1.    0.129 0.918]
 [2.414 2.414 1.428 0.184 7.767 1.    5.428]
 [0.473 0.473 0.237 0.863 1.09  0.184 1.   ]]
iteration 295
delta: 7.363474019459164, sigma: 0.8754447773622992, loss: (0.25833136246414795+0j)
w:[0.96431 0.96431 1.90486 1.1753  0.25248 1.42134 0.36009]
D: [[1.    1.    0.502 3.18  3.157 0.415 2.115]
 [1.    1.    0.502 3.18  3.157 0.415 2.115]
 [1.994 1.994 1.    6.356 6.291 0.701 4.215]
 [0.314 0.314 0.157 1.    1.909 5.421 1.161]
 [0.317 0.317 0.159 0.524 1.    0.129 0.917]
 [2.412 2.412 1.426 0.184 7.764 1.    5.427]
 [0.473 0.473 0.237 0.861 1.09  0.184 1.   ]]
iteration 296
delta: 7.371217745580545, sigma: 

iteration 314
delta: 7.509904223560489, sigma: 0.8902516667697021, loss: (0.25000449950545367+0j)
w:[0.96766 0.96766 1.9115  1.17427 0.25228 1.42019 0.35884]
D: [[1.    1.    0.502 3.136 3.169 0.42  2.126]
 [1.    1.    0.502 3.136 3.169 0.42  2.126]
 [1.994 1.994 1.    6.267 6.315 0.713 4.235]
 [0.319 0.319 0.16  1.    1.96  5.334 1.201]
 [0.316 0.316 0.158 0.51  1.    0.13  0.913]
 [2.384 2.384 1.402 0.187 7.709 1.    5.399]
 [0.47  0.47  0.236 0.833 1.095 0.185 1.   ]]
iteration 315
delta: 7.517569344668435, sigma: 0.8910343542246164, loss: (0.24957542063357657+0j)
w:[0.96784 0.96784 1.91185 1.17421 0.25227 1.42013 0.35878]
D: [[1.    1.    0.502 3.134 3.17  0.42  2.126]
 [1.    1.    0.502 3.134 3.17  0.42  2.126]
 [1.993 1.993 1.    6.262 6.316 0.714 4.236]
 [0.319 0.319 0.16  1.    1.963 5.33  1.203]
 [0.315 0.315 0.158 0.509 1.    0.13  0.913]
 [2.382 2.382 1.401 0.188 7.706 1.    5.398]
 [0.47  0.47  0.236 0.831 1.095 0.185 1.   ]]
iteration 316
delta: 7.525230211346593, sigma:

iteration 336
delta: 7.677537645826235, sigma: 0.9075310844569303, loss: (0.24076779669336823+0j)
w:[0.97143 0.97143 1.91897 1.173   0.25212 1.41896 0.35759]
D: [[1.    1.    0.502 3.086 3.184 0.425 2.138]
 [1.    1.    0.502 3.086 3.184 0.425 2.138]
 [1.993 1.993 1.    6.166 6.343 0.727 4.26 ]
 [0.324 0.324 0.162 1.    2.019 5.236 1.246]
 [0.314 0.314 0.158 0.495 1.    0.131 0.909]
 [2.351 2.351 1.376 0.191 7.647 1.    5.368]
 [0.468 0.468 0.235 0.803 1.1   0.186 1.   ]]
iteration 337
delta: 7.685106732998953, sigma: 0.9083190706862166, loss: (0.24035782738015787+0j)
w:[0.9716  0.9716  1.9193  1.17294 0.25212 1.4189  0.35754]
D: [[1.    1.    0.502 3.083 3.185 0.426 2.139]
 [1.    1.    0.502 3.083 3.185 0.426 2.139]
 [1.993 1.993 1.    6.161 6.344 0.728 4.261]
 [0.324 0.324 0.162 1.    2.022 5.232 1.248]
 [0.314 0.314 0.158 0.495 1.    0.131 0.909]
 [2.35  2.35  1.374 0.191 7.644 1.    5.366]
 [0.468 0.468 0.235 0.801 1.101 0.186 1.   ]]
iteration 338
delta: 7.692671340216733, sigma:

iteration 358
delta: 7.84300881594183, sigma: 0.9249014915868192, loss: (0.23193830162736737+0j)
w:[0.97509 0.97509 1.92621 1.17168 0.25205 1.41783 0.35655]
D: [[1.    1.    0.502 3.037 3.199 0.431 2.151]
 [1.    1.    0.502 3.037 3.199 0.431 2.151]
 [1.993 1.993 1.    6.067 6.371 0.741 4.284]
 [0.329 0.329 0.165 1.    2.076 5.14  1.29 ]
 [0.313 0.313 0.157 0.482 1.    0.132 0.904]
 [2.32  2.32  1.35  0.195 7.588 1.    5.337]
 [0.465 0.465 0.233 0.775 1.106 0.187 1.   ]]
iteration 359
delta: 7.850477293792374, sigma: 0.9256923965892767, loss: (0.23154620760836606+0j)
w:[0.97525 0.97525 1.92653 1.17162 0.25205 1.41778 0.35651]
D: [[1.    1.    0.502 3.034 3.199 0.431 2.152]
 [1.    1.    0.502 3.034 3.199 0.431 2.152]
 [1.993 1.993 1.    6.063 6.372 0.741 4.285]
 [0.33  0.33  0.165 1.    2.079 5.136 1.292]
 [0.313 0.313 0.157 0.481 1.    0.132 0.904]
 [2.319 2.319 1.349 0.195 7.585 1.    5.336]
 [0.465 0.465 0.233 0.774 1.106 0.187 1.   ]]
iteration 360
delta: 7.8579411023181756, sigma:

iteration 377
delta: 7.984104121629883, sigma: 0.9399385452030723, loss: (0.2246206225946443+0j)
w:[0.97816 0.97816 1.93229 1.1705  0.25204 1.41694 0.35579]
D: [[1.    1.    0.502 2.995 3.211 0.436 2.162]
 [1.    1.    0.502 2.995 3.211 0.436 2.162]
 [1.992 1.992 1.    5.984 6.395 0.752 4.305]
 [0.334 0.334 0.167 1.    2.125 5.059 1.328]
 [0.311 0.311 0.156 0.471 1.    0.133 0.901]
 [2.295 2.295 1.329 0.198 7.538 1.    5.312]
 [0.462 0.462 0.232 0.753 1.11  0.188 1.   ]]
iteration 378
delta: 7.991482608692166, sigma: 0.9407302897277054, loss: (0.22424306817084427+0j)
w:[0.97832 0.97832 1.9326  1.17043 0.25204 1.41689 0.35575]
D: [[1.    1.    0.502 2.993 3.212 0.436 2.163]
 [1.    1.    0.502 2.993 3.212 0.436 2.163]
 [1.992 1.992 1.    5.98  6.396 0.753 4.307]
 [0.334 0.334 0.167 1.    2.127 5.055 1.33 ]
 [0.311 0.311 0.156 0.47  1.    0.133 0.901]
 [2.293 2.293 1.328 0.198 7.536 1.    5.311]
 [0.462 0.462 0.232 0.752 1.11  0.188 1.   ]]
iteration 379
delta: 7.998856288845243, sigma: 

iteration 395
delta: 8.116176209353462, sigma: 0.9541876414160024, loss: (0.21793674116294834+0j)
w:[0.98099 0.98099 1.93789 1.16934 0.25207 1.41614 0.35517]
D: [[1.    1.    0.502 2.957 3.223 0.44  2.173]
 [1.    1.    0.502 2.957 3.223 0.44  2.173]
 [1.992 1.992 1.    5.907 6.418 0.763 4.326]
 [0.338 0.338 0.169 1.    2.17  4.983 1.363]
 [0.31  0.31  0.156 0.461 1.    0.133 0.897]
 [2.271 2.271 1.31  0.201 7.493 1.    5.288]
 [0.46  0.46  0.231 0.734 1.114 0.189 1.   ]]
iteration 396
delta: 8.123467206539658, sigma: 0.954978909491354, loss: (0.2175722596600242+0j)
w:[0.98114 0.98114 1.9382  1.16927 0.25207 1.4161  0.35514]
D: [[1.    1.    0.502 2.954 3.224 0.441 2.173]
 [1.    1.    0.502 2.954 3.224 0.441 2.173]
 [1.992 1.992 1.    5.903 6.419 0.764 4.327]
 [0.338 0.338 0.169 1.    2.172 4.979 1.365]
 [0.31  0.31  0.156 0.46  1.    0.134 0.897]
 [2.269 2.269 1.309 0.201 7.49  1.    5.287]
 [0.46  0.46  0.231 0.733 1.115 0.189 1.   ]]
iteration 397
delta: 8.130753286536025, sigma: 0

iteration 415
delta: 8.26105573371531, sigma: 0.9699978532295326, loss: (0.21077934765069878+0j)
w:[0.98414 0.98414 1.94414 1.16812 0.25216 1.41544 0.35463]
D: [[1.    1.    0.502 2.915 3.237 0.445 2.185]
 [1.    1.    0.502 2.915 3.237 0.445 2.185]
 [1.992 1.992 1.    5.823 6.443 0.775 4.348]
 [0.343 0.343 0.172 1.    2.218 4.901 1.401]
 [0.309 0.309 0.155 0.451 1.    0.134 0.894]
 [2.245 2.245 1.29  0.204 7.443 1.    5.262]
 [0.458 0.458 0.23  0.714 1.119 0.19  1.   ]]
iteration 416
delta: 8.268247379944214, sigma: 0.9707873027915612, loss: (0.21042865560335197+0j)
w:[0.9843  0.9843  1.94445 1.16806 0.25217 1.41541 0.35461]
D: [[1.    1.    0.502 2.913 3.237 0.446 2.185]
 [1.    1.    0.502 2.913 3.237 0.446 2.185]
 [1.992 1.992 1.    5.818 6.445 0.776 4.35 ]
 [0.343 0.343 0.172 1.    2.221 4.897 1.403]
 [0.309 0.309 0.155 0.45  1.    0.134 0.893]
 [2.244 2.244 1.289 0.204 7.441 1.    5.261]
 [0.458 0.458 0.23  0.713 1.119 0.19  1.   ]]
iteration 417
delta: 8.275434006656514, sigma: 

iteration 433
delta: 8.389733782474407, sigma: 0.9841866371256544, loss: (0.2045680121987442+0j)
w:[0.98694 0.98694 1.94968 1.16703 0.25229 1.4149  0.35424]
D: [[1.    1.    0.502 2.878 3.249 0.45  2.195]
 [1.    1.    0.502 2.878 3.249 0.45  2.195]
 [1.991 1.991 1.    5.748 6.466 0.786 4.369]
 [0.348 0.348 0.174 1.    2.261 4.828 1.435]
 [0.308 0.308 0.155 0.442 1.    0.135 0.89 ]
 [2.223 2.223 1.272 0.207 7.4   1.    5.24 ]
 [0.456 0.456 0.229 0.697 1.123 0.191 1.   ]]
iteration 434
delta: 8.396834414196192, sigma: 0.984973418199287, loss: (0.20422911888177042+0j)
w:[0.98709 0.98709 1.94998 1.16697 0.2523  1.41487 0.35422]
D: [[1.    1.    0.502 2.876 3.249 0.45  2.196]
 [1.    1.    0.502 2.876 3.249 0.45  2.196]
 [1.991 1.991 1.    5.744 6.467 0.787 4.37 ]
 [0.348 0.348 0.174 1.    2.264 4.824 1.437]
 [0.308 0.308 0.155 0.442 1.    0.135 0.89 ]
 [2.222 2.222 1.271 0.207 7.398 1.    5.239]
 [0.455 0.455 0.229 0.696 1.123 0.191 1.   ]]
iteration 435
delta: 8.403929951002246, sigma: 0

iteration 452
delta: 8.523771077111661, sigma: 0.9991031031560251, loss: (0.19823680202511157+0j)
w:[0.98982 0.98982 1.95538 1.16584 0.25246 1.41435 0.3539 ]
D: [[1.    1.    0.502 2.839 3.261 0.455 2.206]
 [1.    1.    0.502 2.839 3.261 0.455 2.206]
 [1.991 1.991 1.    5.672 6.49  0.797 4.39 ]
 [0.352 0.352 0.176 1.    2.306 4.753 1.47 ]
 [0.307 0.307 0.154 0.434 1.    0.136 0.887]
 [2.2   2.2   1.254 0.21  7.356 1.    5.216]
 [0.453 0.453 0.228 0.68  1.127 0.192 1.   ]]
iteration 453
delta: 8.53077430374191, sigma: 0.9998861274653456, loss: (0.1979097813986145+0j)
w:[0.98997 0.98997 1.95567 1.16578 0.25247 1.41432 0.35389]
D: [[1.    1.    0.502 2.837 3.262 0.455 2.207]
 [1.    1.    0.502 2.837 3.262 0.455 2.207]
 [1.991 1.991 1.    5.668 6.491 0.798 4.392]
 [0.352 0.352 0.176 1.    2.308 4.749 1.472]
 [0.307 0.307 0.154 0.433 1.    0.136 0.887]
 [2.199 2.199 1.253 0.211 7.353 1.    5.215]
 [0.453 0.453 0.228 0.679 1.128 0.192 1.   ]]
iteration 454
delta: 8.537772371234421, sigma: 1

iteration 471
delta: 8.655947439025919, sigma: 1.0139403165293976, loss: (0.1921261164528577+0j)
w:[0.99262 0.99262 1.96093 1.16462 0.25265 1.41383 0.35364]
D: [[1.    1.    0.502 2.802 3.274 0.459 2.218]
 [1.    1.    0.502 2.802 3.274 0.459 2.218]
 [1.991 1.991 1.    5.597 6.514 0.808 4.412]
 [0.357 0.357 0.179 1.    2.349 4.679 1.504]
 [0.305 0.305 0.154 0.426 1.    0.137 0.884]
 [2.178 2.178 1.237 0.214 7.313 1.    5.193]
 [0.451 0.451 0.227 0.665 1.132 0.193 1.   ]]
iteration 472
delta: 8.66285217081358, sigma: 1.014718727619108, loss: (0.1918104138900944+0j)
w:[0.99277 0.99277 1.96121 1.16456 0.25266 1.4138  0.35363]
D: [[1.    1.    0.502 2.8   3.274 0.459 2.218]
 [1.    1.    0.502 2.8   3.274 0.459 2.218]
 [1.991 1.991 1.    5.593 6.515 0.809 4.413]
 [0.357 0.357 0.179 1.    2.352 4.675 1.506]
 [0.305 0.305 0.153 0.425 1.    0.137 0.884]
 [2.177 2.177 1.236 0.214 7.31  1.    5.192]
 [0.451 0.451 0.227 0.664 1.132 0.193 1.   ]]
iteration 473
delta: 8.669751693478652, sigma: 1.0

iteration 491
delta: 8.793049927451154, sigma: 1.0294559600474646, loss: (0.18592087469699198+0j)
w:[0.99549 0.99549 1.96661 1.1633  0.25287 1.41331 0.35343]
D: [[1.    1.    0.502 2.763 3.287 0.464 2.229]
 [1.    1.    0.502 2.763 3.287 0.464 2.229]
 [1.991 1.991 1.    5.519 6.539 0.82  4.435]
 [0.362 0.362 0.181 1.    2.394 4.603 1.54 ]
 [0.304 0.304 0.153 0.418 1.    0.138 0.88 ]
 [2.155 2.155 1.22  0.217 7.268 1.    5.17 ]
 [0.449 0.449 0.225 0.649 1.136 0.193 1.   ]]
iteration 492
delta: 8.799850085797555, sigma: 1.0302286993198668, loss: (0.1856165294824246+0j)
w:[0.99563 0.99563 1.96689 1.16324 0.25288 1.41328 0.35342]
D: [[1.    1.    0.502 2.761 3.288 0.464 2.23 ]
 [1.    1.    0.502 2.761 3.288 0.464 2.23 ]
 [1.991 1.991 1.    5.515 6.54  0.82  4.436]
 [0.362 0.362 0.181 1.    2.396 4.599 1.541]
 [0.304 0.304 0.153 0.417 1.    0.138 0.88 ]
 [2.154 2.154 1.219 0.217 7.266 1.    5.169]
 [0.448 0.448 0.225 0.649 1.136 0.193 1.   ]]
iteration 493
delta: 8.80664499608146, sigma: 1

iteration 509
delta: 8.914648638330002, sigma: 1.0433173533803237, loss: (0.18052630110066586+0j)
w:[0.99801 0.99801 1.97159 1.16209 0.25309 1.41285 0.35329]
D: [[1.    1.    0.502 2.729 3.299 0.468 2.24 ]
 [1.    1.    0.502 2.729 3.299 0.468 2.24 ]
 [1.99  1.99  1.    5.451 6.561 0.83  4.455]
 [0.366 0.366 0.183 1.    2.433 4.535 1.571]
 [0.303 0.303 0.152 0.411 1.    0.138 0.878]
 [2.135 2.135 1.205 0.221 7.229 1.    5.149]
 [0.446 0.446 0.224 0.637 1.14  0.194 1.   ]]
iteration 510
delta: 8.921354115253278, sigma: 1.0440843573688718, loss: (0.18023172275834884+0j)
w:[0.99814 0.99814 1.97186 1.16202 0.2531  1.41282 0.35329]
D: [[1.    1.    0.502 2.727 3.299 0.469 2.241]
 [1.    1.    0.502 2.727 3.299 0.469 2.241]
 [1.99  1.99  1.    5.447 6.562 0.831 4.456]
 [0.367 0.367 0.184 1.    2.435 4.531 1.573]
 [0.303 0.303 0.152 0.411 1.    0.138 0.877]
 [2.134 2.134 1.204 0.221 7.227 1.    5.148]
 [0.446 0.446 0.224 0.636 1.14  0.194 1.   ]]
iteration 511
delta: 8.928054320237369, sigma:

iteration 529
delta: 9.04775544788845, sigma: 1.0585920625247165, loss: (0.1747341485331473+0j)
w:[1.00073 1.00073 1.97698 1.16071 0.25335 1.41235 0.35319]
D: [[1.    1.    0.503 2.692 3.311 0.473 2.252]
 [1.    1.    0.503 2.692 3.311 0.473 2.252]
 [1.99  1.99  1.    5.377 6.586 0.841 4.477]
 [0.371 0.371 0.186 1.    2.476 4.462 1.605]
 [0.302 0.302 0.152 0.404 1.    0.139 0.874]
 [2.114 2.114 1.189 0.224 7.187 1.    5.126]
 [0.444 0.444 0.223 0.623 1.144 0.195 1.   ]]
iteration 530
delta: 9.054355318362234, sigma: 1.0593520793104856, loss: (0.17444995082690642+0j)
w:[1.00086 1.00086 1.97724 1.16064 0.25337 1.41233 0.35319]
D: [[1.    1.    0.503 2.691 3.312 0.473 2.252]
 [1.    1.    0.503 2.691 3.312 0.473 2.252]
 [1.99  1.99  1.    5.373 6.587 0.842 4.479]
 [0.372 0.372 0.186 1.    2.478 4.458 1.607]
 [0.302 0.302 0.152 0.404 1.    0.139 0.874]
 [2.113 2.113 1.188 0.224 7.185 1.    5.125]
 [0.444 0.444 0.223 0.622 1.144 0.195 1.   ]]
iteration 531
delta: 9.060949901151584, sigma: 1

iteration 548
delta: 9.17224839331018, sigma: 1.0729686667390697, loss: (0.16941991364120731+0j)
w:[1.00325 1.00325 1.98196 1.15938 0.25362 1.41189 0.35315]
D: [[1.    1.    0.503 2.658 3.323 0.478 2.263]
 [1.    1.    0.503 2.658 3.323 0.478 2.263]
 [1.99  1.99  1.    5.307 6.609 0.852 4.499]
 [0.376 0.376 0.188 1.    2.515 4.393 1.637]
 [0.301 0.301 0.151 0.398 1.    0.14  0.871]
 [2.094 2.094 1.174 0.228 7.148 1.    5.105]
 [0.442 0.442 0.222 0.611 1.148 0.196 1.   ]]
iteration 549
delta: 9.17874773479302, sigma: 1.0737215204591601, loss: (0.1691451472027707+0j)
w:[1.00338 1.00338 1.98222 1.15931 0.25363 1.41187 0.35314]
D: [[1.    1.    0.503 2.656 3.324 0.478 2.263]
 [1.    1.    0.503 2.656 3.324 0.478 2.263]
 [1.99  1.99  1.    5.304 6.61  0.852 4.5  ]
 [0.376 0.376 0.189 1.    2.518 4.389 1.638]
 [0.301 0.301 0.151 0.397 1.    0.14  0.871]
 [2.093 2.093 1.173 0.228 7.146 1.    5.104]
 [0.442 0.442 0.222 0.61  1.148 0.196 1.   ]]
iteration 550
delta: 9.185241783002299, sigma: 1.

iteration 566
delta: 9.288426724156341, sigma: 1.086459409365327, loss: (0.1645474921274755+0j)
w:[1.00557 1.00557 1.98656 1.1581  0.25388 1.41146 0.35314]
D: [[1.    1.    0.503 2.626 3.335 0.482 2.273]
 [1.    1.    0.503 2.626 3.335 0.482 2.273]
 [1.989 1.989 1.    5.243 6.63  0.862 4.519]
 [0.381 0.381 0.191 1.    2.552 4.329 1.666]
 [0.3   0.3   0.151 0.392 1.    0.141 0.869]
 [2.076 2.076 1.16  0.231 7.112 1.    5.085]
 [0.44  0.44  0.221 0.6   1.151 0.197 1.   ]]
iteration 567
delta: 9.294830800792344, sigma: 1.087205065001571, loss: (0.16428129776297595+0j)
w:[1.0057  1.0057  1.98681 1.15803 0.2539  1.41144 0.35314]
D: [[1.    1.    0.503 2.624 3.335 0.482 2.274]
 [1.    1.    0.503 2.624 3.335 0.482 2.274]
 [1.989 1.989 1.    5.24  6.631 0.862 4.52 ]
 [0.381 0.381 0.191 1.    2.554 4.326 1.668]
 [0.3   0.3   0.151 0.392 1.    0.141 0.868]
 [2.075 2.075 1.16  0.231 7.11  1.    5.084]
 [0.44  0.44  0.221 0.6   1.151 0.197 1.   ]]
iteration 568
delta: 9.301229586900643, sigma: 1.

iteration 585
delta: 9.409199919537338, sigma: 1.100555647694459, loss: (0.15956855826492278+0j)
w:[1.00796 1.00796 1.9913  1.15673 0.25417 1.41101 0.35316]
D: [[1.    1.    0.503 2.593 3.347 0.486 2.284]
 [1.    1.    0.503 2.593 3.347 0.486 2.284]
 [1.989 1.989 1.    5.177 6.653 0.872 4.54 ]
 [0.386 0.386 0.193 1.    2.59  4.263 1.696]
 [0.299 0.299 0.15  0.386 1.    0.141 0.866]
 [2.057 2.057 1.147 0.235 7.075 1.    5.065]
 [0.438 0.438 0.22  0.59  1.155 0.197 1.   ]]
iteration 586
delta: 9.415503555869677, sigma: 1.1012933265279232, loss: (0.15931105187641736+0j)
w:[1.00809 1.00809 1.99154 1.15665 0.25418 1.41099 0.35317]
D: [[1.    1.    0.503 2.591 3.347 0.486 2.285]
 [1.    1.    0.503 2.591 3.347 0.486 2.285]
 [1.989 1.989 1.    5.174 6.654 0.873 4.541]
 [0.386 0.386 0.193 1.    2.592 4.26  1.698]
 [0.299 0.299 0.15  0.386 1.    0.141 0.866]
 [2.056 2.056 1.146 0.235 7.073 1.    5.064]
 [0.438 0.438 0.22  0.589 1.155 0.197 1.   ]]
iteration 587
delta: 9.421801911783898, sigma: 

iteration 603
delta: 9.521858118326495, sigma: 1.1137674035633671, loss: (0.15500112183328343+0j)
w:[1.01018 1.01018 1.99567 1.15541 0.25445 1.41059 0.35322]
D: [[1.    1.    0.503 2.562 3.358 0.49  2.294]
 [1.    1.    0.503 2.562 3.358 0.49  2.294]
 [1.989 1.989 1.    5.115 6.674 0.882 4.559]
 [0.39  0.39  0.195 1.    2.625 4.202 1.724]
 [0.298 0.298 0.15  0.381 1.    0.142 0.863]
 [2.04  2.04  1.134 0.238 7.04  1.    5.045]
 [0.436 0.436 0.219 0.58  1.158 0.198 1.   ]]
iteration 604
delta: 9.528066833174657, sigma: 1.1144972137008116, loss: (0.15475152409118342+0j)
w:[1.0103  1.0103  1.99591 1.15534 0.25447 1.41056 0.35322]
D: [[1.    1.    0.503 2.56  3.358 0.49  2.295]
 [1.    1.    0.503 2.56  3.358 0.49  2.295]
 [1.989 1.989 1.    5.112 6.675 0.882 4.56 ]
 [0.391 0.391 0.196 1.    2.627 4.198 1.726]
 [0.298 0.298 0.15  0.381 1.    0.142 0.863]
 [2.039 2.039 1.133 0.238 7.038 1.    5.044]
 [0.436 0.436 0.219 0.579 1.159 0.198 1.   ]]
iteration 605
delta: 9.534270283455207, sigma:

iteration 621
delta: 9.632810413602542, sigma: 1.1268352400398218, loss: (0.15057349978685344+0j)
w:[1.01233 1.01233 1.99994 1.15408 0.25474 1.41016 0.3533 ]
D: [[1.    1.    0.503 2.532 3.369 0.494 2.304]
 [1.    1.    0.503 2.532 3.369 0.494 2.304]
 [1.989 1.989 1.    5.055 6.695 0.891 4.579]
 [0.395 0.395 0.198 1.    2.659 4.141 1.752]
 [0.297 0.297 0.149 0.376 1.    0.143 0.861]
 [2.023 2.023 1.122 0.241 7.006 1.    5.027]
 [0.434 0.434 0.218 0.571 1.162 0.199 1.   ]]
iteration 622
delta: 9.638924539986341, sigma: 1.1275569197241495, loss: (0.15033151457725719+0j)
w:[1.01245 1.01245 2.00018 1.15401 0.25475 1.41014 0.3533 ]
D: [[1.    1.    0.503 2.53  3.369 0.494 2.305]
 [1.    1.    0.503 2.53  3.369 0.494 2.305]
 [1.989 1.989 1.    5.052 6.696 0.892 4.58 ]
 [0.395 0.395 0.198 1.    2.661 4.138 1.754]
 [0.297 0.297 0.149 0.376 1.    0.143 0.861]
 [2.022 2.022 1.121 0.242 7.004 1.    5.026]
 [0.434 0.434 0.218 0.57  1.162 0.199 1.   ]]
iteration 623
delta: 9.645033423119756, sigma:

iteration 640
delta: 9.748083581697022, sigma: 1.1404680892488106, loss: (0.14604584334173187+0j)
w:[1.01455 1.01455 2.00434 1.15267 0.25505 1.40971 0.35341]
D: [[1.    1.    0.503 2.501 3.38  0.498 2.315]
 [1.    1.    0.503 2.501 3.38  0.498 2.315]
 [1.988 1.988 1.    4.992 6.717 0.901 4.599]
 [0.4   0.4   0.2   1.    2.694 4.079 1.78 ]
 [0.296 0.296 0.149 0.371 1.    0.143 0.858]
 [2.006 2.006 1.11  0.245 6.971 1.    5.007]
 [0.432 0.432 0.217 0.562 1.165 0.2   1.   ]]
iteration 641
delta: 9.754098330380884, sigma: 1.1411809435826077, loss: (0.1458115895517229+0j)
w:[1.01467 1.01467 2.00456 1.15259 0.25506 1.40969 0.35341]
D: [[1.    1.    0.503 2.499 3.381 0.499 2.316]
 [1.    1.    0.503 2.499 3.381 0.499 2.316]
 [1.988 1.988 1.    4.989 6.718 0.902 4.601]
 [0.4   0.4   0.2   1.    2.696 4.075 1.782]
 [0.296 0.296 0.149 0.371 1.    0.143 0.858]
 [2.005 2.005 1.109 0.245 6.969 1.    5.006]
 [0.432 0.432 0.217 0.561 1.166 0.2   1.   ]]
iteration 642
delta: 9.760107863995781, sigma: 

iteration 661
delta: 9.873300323829778, sigma: 1.155338451602138, loss: (0.14120914489547198+0j)
w:[1.01694 1.01694 2.00906 1.15109 0.2554  1.40921 0.35356]
D: [[1.    1.    0.503 2.467 3.393 0.503 2.327]
 [1.    1.    0.503 2.467 3.393 0.503 2.327]
 [1.988 1.988 1.    4.925 6.741 0.912 4.622]
 [0.405 0.405 0.203 1.    2.732 4.011 1.811]
 [0.295 0.295 0.148 0.366 1.    0.144 0.855]
 [1.988 1.988 1.096 0.249 6.933 1.    4.986]
 [0.43  0.43  0.216 0.552 1.169 0.201 1.   ]]
iteration 662
delta: 9.879205908135628, sigma: 1.1560413073298708, loss: (0.1409830930469997+0j)
w:[1.01705 1.01705 2.00928 1.15102 0.25541 1.40918 0.35356]
D: [[1.    1.    0.503 2.466 3.393 0.503 2.327]
 [1.    1.    0.503 2.466 3.393 0.503 2.327]
 [1.988 1.988 1.    4.922 6.742 0.913 4.623]
 [0.406 0.406 0.203 1.    2.734 4.008 1.813]
 [0.295 0.295 0.148 0.366 1.    0.144 0.855]
 [1.987 1.987 1.096 0.25  6.932 1.    4.985]
 [0.43  0.43  0.216 0.552 1.169 0.201 1.   ]]
iteration 663
delta: 9.88510631373542, sigma: 1.

iteration 679
delta: 9.978810079236435, sigma: 1.1679157797778383, loss: (0.1371980250642441+0j)
w:[1.01893 1.01893 2.01301 1.14974 0.2557  1.40877 0.3537 ]
D: [[1.    1.    0.503 2.439 3.403 0.507 2.336]
 [1.    1.    0.503 2.439 3.403 0.507 2.336]
 [1.988 1.988 1.    4.868 6.761 0.921 4.641]
 [0.41  0.41  0.205 1.    2.763 3.954 1.837]
 [0.294 0.294 0.148 0.362 1.    0.145 0.853]
 [1.972 1.972 1.085 0.253 6.902 1.    4.968]
 [0.428 0.428 0.215 0.544 1.173 0.201 1.   ]]
iteration 680
delta: 9.984622745407655, sigma: 1.1686098960759106, loss: (0.1369787319308905+0j)
w:[1.01904 1.01904 2.01322 1.14966 0.25572 1.40874 0.35371]
D: [[1.    1.    0.503 2.438 3.404 0.507 2.337]
 [1.    1.    0.503 2.438 3.404 0.507 2.337]
 [1.988 1.988 1.    4.865 6.762 0.922 4.642]
 [0.41  0.41  0.206 1.    2.765 3.951 1.838]
 [0.294 0.294 0.148 0.362 1.    0.145 0.853]
 [1.972 1.972 1.085 0.253 6.9   1.    4.967]
 [0.428 0.428 0.215 0.544 1.173 0.201 1.   ]]
iteration 681
delta: 9.99043026860619, sigma: 1.

iteration 698
delta: 10.088373354095957, sigma: 1.1810199246762725, loss: (0.13309375168725418+0j)
w:[1.02099 1.02099 2.01707 1.14829 0.25602 1.4083  0.35387]
D: [[1.    1.    0.503 2.41  3.414 0.511 2.347]
 [1.    1.    0.503 2.41  3.414 0.511 2.347]
 [1.988 1.988 1.    4.81  6.782 0.931 4.661]
 [0.415 0.415 0.208 1.    2.796 3.895 1.864]
 [0.293 0.293 0.147 0.358 1.    0.146 0.85 ]
 [1.957 1.957 1.074 0.257 6.869 1.    4.949]
 [0.426 0.426 0.215 0.537 1.176 0.202 1.   ]]
iteration 699
delta: 10.094088671345677, sigma: 1.1817046781158747, loss: (0.13288133507700434+0j)
w:[1.02109 1.02109 2.01728 1.14822 0.25604 1.40827 0.35388]
D: [[1.    1.    0.503 2.408 3.415 0.511 2.347]
 [1.    1.    0.503 2.408 3.415 0.511 2.347]
 [1.988 1.988 1.    4.806 6.783 0.931 4.662]
 [0.415 0.415 0.208 1.    2.798 3.892 1.865]
 [0.293 0.293 0.147 0.357 1.    0.146 0.85 ]
 [1.956 1.956 1.074 0.257 6.867 1.    4.949]
 [0.426 0.426 0.215 0.536 1.176 0.202 1.   ]]
iteration 700
delta: 10.099798887161034, sig

iteration 717
delta: 10.196094278236089, sigma: 1.193945111129548, loss: (0.1291178477878303+0j)
w:[1.02299 1.02299 2.02102 1.14684 0.25635 1.40782 0.35406]
D: [[1.    1.    0.503 2.381 3.425 0.515 2.357]
 [1.    1.    0.503 2.381 3.425 0.515 2.357]
 [1.988 1.988 1.    4.752 6.802 0.94  4.68 ]
 [0.42  0.42  0.21  1.    2.828 3.837 1.889]
 [0.292 0.292 0.147 0.354 1.    0.146 0.848]
 [1.941 1.941 1.063 0.261 6.837 1.    4.931]
 [0.424 0.424 0.214 0.529 1.179 0.203 1.   ]]
iteration 718
delta: 10.201713066884771, sigma: 1.1946203882543416, loss: (0.12891205611953388+0j)
w:[1.02309 1.02309 2.02123 1.14677 0.25637 1.40779 0.35407]
D: [[1.    1.    0.503 2.38  3.426 0.515 2.357]
 [1.    1.    0.503 2.38  3.426 0.515 2.357]
 [1.987 1.987 1.    4.749 6.804 0.941 4.681]
 [0.42  0.42  0.211 1.    2.829 3.834 1.891]
 [0.292 0.292 0.147 0.353 1.    0.146 0.848]
 [1.94  1.94  1.063 0.261 6.835 1.    4.93 ]
 [0.424 0.424 0.214 0.529 1.179 0.203 1.   ]]
iteration 719
delta: 10.207326799038512, sigma

w:[1.02493 1.02493 2.02488 1.14539 0.25667 1.40733 0.35426]
D: [[1.    1.    0.503 2.353 3.436 0.519 2.367]
 [1.    1.    0.503 2.353 3.436 0.519 2.367]
 [1.987 1.987 1.    4.696 6.823 0.95  4.7  ]
 [0.425 0.425 0.213 1.    2.858 3.78  1.915]
 [0.291 0.291 0.147 0.35  1.    0.147 0.846]
 [1.926 1.926 1.053 0.265 6.805 1.    4.913]
 [0.422 0.422 0.213 0.522 1.182 0.204 1.   ]]
iteration 737
delta: 10.307512159351525, sigma: 1.2073551340786703, loss: (0.12506623996249716+0j)
w:[1.02503 1.02503 2.02508 1.14532 0.25669 1.4073  0.35427]
D: [[1.    1.    0.503 2.352 3.436 0.519 2.368]
 [1.    1.    0.503 2.352 3.436 0.519 2.368]
 [1.987 1.987 1.    4.693 6.824 0.95  4.701]
 [0.425 0.425 0.213 1.    2.86  3.777 1.916]
 [0.291 0.291 0.147 0.35  1.    0.147 0.846]
 [1.926 1.926 1.052 0.265 6.804 1.    4.912]
 [0.422 0.422 0.213 0.522 1.183 0.204 1.   ]]
iteration 738
delta: 10.313030294466056, sigma: 1.2080203420071192, loss: (0.12486716369042841+0j)
w:[1.02514 1.02514 2.02528 1.14524 0.25671 1

iteration 756
delta: 10.411503302846018, sigma: 1.219907489637231, loss: (0.12133945740754054+0j)
w:[1.02693 1.02693 2.02883 1.14386 0.25702 1.4068  0.35448]
D: [[1.    1.    0.503 2.324 3.447 0.523 2.377]
 [1.    1.    0.503 2.324 3.447 0.523 2.377]
 [1.987 1.987 1.    4.638 6.844 0.959 4.72 ]
 [0.43  0.43  0.216 1.    2.89  3.721 1.941]
 [0.29  0.29  0.146 0.346 1.    0.148 0.843]
 [1.911 1.911 1.042 0.269 6.773 1.    4.895]
 [0.421 0.421 0.212 0.515 1.186 0.204 1.   ]]
iteration 757
delta: 10.416926782895143, sigma: 1.220563066743561, loss: (0.12114652742160499+0j)
w:[1.02703 1.02703 2.02902 1.14378 0.25703 1.40677 0.35449]
D: [[1.    1.    0.503 2.323 3.447 0.523 2.378]
 [1.    1.    0.503 2.323 3.447 0.523 2.378]
 [1.987 1.987 1.    4.635 6.845 0.96  4.721]
 [0.43  0.43  0.216 1.    2.892 3.718 1.942]
 [0.29  0.29  0.146 0.346 1.    0.148 0.843]
 [1.91  1.91  1.042 0.269 6.771 1.    4.894]
 [0.421 0.421 0.212 0.515 1.186 0.204 1.   ]]
iteration 758
delta: 10.42234530784376, sigma:

KeyboardInterrupt: 